version: "2"
checks:
  file-lines:
    enabled: true
    config:
      threshold: 500
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 30
  similar-code:
    enabled: true
    config:
      threshold: 6
exclude_patterns:
  - "**/**/__tests__/"
  - "**/**/migrations/**"
  - "utility/*"
  - "**/**/urls.py"
  - "**/**/**/serializers/serializer*"
  - "**/**/**/viewsets.py"
  - "config/settings/*"
  - "**/**/admin.py"
