language: python
python:
  - "3.6"
install:
  - pip install -r requirements/local.txt
script:
  - pytest
  - docker build -t marcelomaia/terceirizadas_backend .
  - docker run -d -p 8000:8000 marcelomaia/terceirizadas_backend python manage.py runserver --settings=config.settings.local
  - docker ps -a
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push marcelomaia/terceirizadas_backend
  on:
    branch: development
