# Use postgres/example user/password credentials
version: '3.1'

services:
  redis:
    image: redis:5.0.5-alpine

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  backend:
    image: marcelomaia/terceirizadas_backend:latest
    # http://docs.gunicorn.org/en/latest/design.html#how-many-workers
    # http://docs.gunicorn.org/en/latest/settings.html#worker-class
    command: "gunicorn config.wsgi:application --bind=0.0.0.0:8000 -w 9"
    ports:
      - 7777:8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_DEBUG=False
      - DJANGO_READ_DOT_ENV_FILE=false
